###numpy: python's compution libs
* 属性
* 运算

In [11]:
import numpy as np

In [8]:
list = [1,2,3]

In [2]:
print(list)

[1, 2, 3]


In [3]:
type(list)

list

In [10]:
array = np.array(list)
print(array)

[1 2 3]


In [6]:
type(array)

numpy.ndarray

List and array difference

In [14]:
np.shape(array)

(3,)

In [15]:
array.shape

(3,)

In [16]:
mul_array = np.array([[1,2,3],[4,5,6]])

In [17]:
print(mul_array)

[[1 2 3]
 [4 5 6]]


In [18]:
mul_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
mul_array.dtype

dtype('int32')

List 存放的内容是多样的，而array里存放的内容则类型必须是统一的。array里支持的类型有哪些？

In [20]:
mul_array.itemsize

4

In [21]:
mul_array.shape

(2, 3)

In [22]:
mul_array.size

6

In [23]:
mul_array.ndim

2

In [24]:
mul_array.fill(0)

In [25]:
print(mul_array)

[[0 0 0]
 [0 0 0]]


In [26]:
mul_array = np.array([[1,2,3],[4,5,6]])

In [27]:
print(mul_array)

[[1 2 3]
 [4 5 6]]


In [29]:
mul_array[1]

array([4, 5, 6])

In [30]:
mul_array[1,0]

4

In [33]:
mul_array[:,2]

array([3, 6])

In [34]:
mul_array[1,1] = 300
mul_array

array([[  1,   2,   3],
       [  4, 300,   6]])

In [35]:
A = mul_array
A

array([[  1,   2,   3],
       [  4, 300,   6]])

In [36]:
A[1,1] = 0
A

array([[1, 2, 3],
       [4, 0, 6]])

In [37]:
mul_array

array([[1, 2, 3],
       [4, 0, 6]])

A ?? ==  mul_array 相当于C里面的指针

In [38]:
A = mul_array.copy()

In [39]:
A

array([[1, 2, 3],
       [4, 0, 6]])

In [40]:
A[1,1] = 10
A

array([[ 1,  2,  3],
       [ 4, 10,  6]])

In [41]:
mul_array

array([[1, 2, 3],
       [4, 0, 6]])

以上采用的是深度复制，备份了另外一份，不共享地址

创建array的方法：

In [42]:
A1 = np.array([1,2])

In [44]:
A2 = np.arange(0,9,1).reshape(3,3)
A2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
random_array = np.random.rand(10)
random_array

array([0.51156785, 0.06228616, 0.488194  , 0.62330313, 0.64708102,
       0.80523862, 0.61228241, 0.12928965, 0.7268473 , 0.34563186])

In [48]:
mask = random_array > 0.5
mask

array([ True, False, False,  True,  True,  True,  True, False,  True,
       False])

In [51]:
random_array[mask]

array([0.51156785, 0.62330313, 0.64708102, 0.80523862, 0.61228241,
       0.7268473 ])

In [52]:
random_array

array([0.51156785, 0.06228616, 0.488194  , 0.62330313, 0.64708102,
       0.80523862, 0.61228241, 0.12928965, 0.7268473 , 0.34563186])

In [54]:
np.where(random_array > 0.6)

(array([3, 4, 5, 6, 8], dtype=int64),)

In [56]:
A1 = np.array([1,2,3], dtype=np.float32)
A1

array([1., 2., 3.], dtype=float32)

In [58]:
A1.dtype

dtype('float32')

In [59]:
A1.nbytes

12

In [60]:
A1 * 2

array([2., 4., 6.], dtype=float32)

In [64]:
A2 = np.asanyarray(A1,dtype = np.int32)
A2.dtype

dtype('int32')

In [65]:
A1

array([1., 2., 3.], dtype=float32)

In [66]:
np.sum(A1)

6.0

In [67]:
mul_array

array([[1, 2, 3],
       [4, 0, 6]])

In [68]:
np.sum(mul_array,axis = 0)

array([5, 2, 9])

In [69]:
np.sum(mul_array, axis = 1)

array([ 6, 10])

In [70]:
mul_array.ndim

2

In [71]:
np.sum(mul_array,axis= -1)

array([ 6, 10])

In [72]:
mul_array.prod()

0

In [73]:
mul_array[1,1] = 1
mul_array

array([[1, 2, 3],
       [4, 1, 6]])

In [74]:
mul_array.prod()

144

In [75]:
mul_array.min()

1

In [76]:
mul_array.min(axis = 0)

array([1, 1, 3])

In [77]:
mul_array.max(axis = 1)

array([3, 6])

In [78]:
mul_array.argmin()  #find the index

0

In [79]:
mul_array.argmax()  

5

In [80]:
mul_array.argmax(axis = 1)

array([2, 2], dtype=int64)

In [81]:
mul_array.mean()

2.8333333333333335

In [82]:
mul_array.std()  #标准差

1.7716909687891083

In [83]:
mul_array.var()  #方差

3.1388888888888893

In [84]:
mul_array

array([[1, 2, 3],
       [4, 1, 6]])

In [86]:
mul_array.clip(2,4)  # 限制数据的大小

array([[2, 2, 3],
       [4, 2, 4]])

In [87]:
mul_array.round()  # 四舍五入

array([[1, 2, 3],
       [4, 1, 6]])

In [88]:
mul_array.round(decimals = 1)  # 设置四舍五入的精度

array([[1, 2, 3],
       [4, 1, 6]])

In [89]:
np.sort(mul_array)

array([[1, 2, 3],
       [1, 4, 6]])

In [90]:
mul_array

array([[1, 2, 3],
       [4, 1, 6]])

In [96]:
mul_array[0,0] = 4
mul_array[1,0] = 0
mul_array

array([[4, 2, 3],
       [0, 1, 6]])

In [97]:
np.sort(mul_array)

array([[2, 3, 4],
       [0, 1, 6]])

In [99]:
np.sort(mul_array, axis = 0)

array([[0, 1, 3],
       [4, 2, 6]])

In [103]:
A3 = np.linspace(0,10,10)
A3

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [112]:
A4 =  np.array([2.1,7.8,5.7])
A4

array([2.1, 7.8, 5.7])

In [114]:
np.searchsorted(A3,A4)

array([2, 8, 6], dtype=int64)

In [115]:
mul_array = np.arange(12).reshape(3,4)
mul_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

对向量操作

In [125]:
array = np.arange(9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [126]:
array.shape

(9,)

In [127]:
array.shape = 3,3

In [128]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [129]:
array_2 = np.arange(12)
array_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [130]:
array_2.shape

(12,)

In [136]:
array_3 = array_2[:,np.newaxis]
array_3

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [135]:
array_3.shape

(12, 1)

In [138]:
array_3 = array_2[np.newaxis,:]
array_3.shape

(1, 12)

In [140]:
array_3 = array_3.squeeze()
array_3.shape

(12,)

In [141]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [142]:
array.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [143]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [144]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [145]:
b = np.arange(9,15).reshape(2,3)
b

array([[ 9, 10, 11],
       [12, 13, 14]])

In [146]:
c = np.concatenate((a,b),axis = 0)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [12, 13, 14]])

In [147]:
c.shape

(4, 3)

In [148]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [12, 13, 14]])

In [149]:
np.hstack((a,b))

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14]])

In [153]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [155]:
a.ravel()

array([0, 1, 2, 3, 4, 5])

矩阵的创建

In [157]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
a2 = np.arange(1,10,2)
a2

array([1, 3, 5, 7, 9])

In [162]:
a3 = np.arange(1,10,3,dtype=np.float32)
a3

array([1., 4., 7.], dtype=float32)

In [163]:
a4 = np.arange(9).reshape(3,3)
a4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [166]:
a5 = np.linspace(0,10,10)  #既包头，也包裹尾
a5

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [167]:
a6 = np.logspace(1,5,10)
a6

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [176]:
x = np.linspace(0,10,5)
x

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [177]:
y = np.linspace(0,10,5)
y

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [178]:
x,y = np.meshgrid(x, y)

In [179]:
x

array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 0. ,  2.5,  5. ,  7.5, 10. ]])

In [180]:
y

array([[ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 2.5,  2.5,  2.5,  2.5,  2.5],
       [ 5. ,  5. ,  5. ,  5. ,  5. ],
       [ 7.5,  7.5,  7.5,  7.5,  7.5],
       [10. , 10. , 10. , 10. , 10. ]])

In [184]:
np.r_[0:10:2]

array([0, 2, 4, 6, 8])

In [186]:
np.c_[0:10:3]

array([[0],
       [3],
       [6],
       [9]])

常用函数

In [192]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [193]:
np.ones((3,9),dtype = np.float32)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)

In [194]:
a = np.empty(4)
a

array([ 2.5,  5. ,  7.5, 10. ])

In [195]:
a.fill(1)
a

array([1., 1., 1., 1.])

In [196]:
np.zeros_like(a)

array([0., 0., 0., 0.])

In [197]:
np.ones_like(a)

array([1., 1., 1., 1.])

In [198]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

四则运算

In [199]:
a = np.array([2,3])
b = np.array([4,6])

In [200]:
np.multiply(a,b)

array([ 8, 18])

In [201]:
np.dot(a,b)

26

In [202]:
b.T
b

array([4, 6])

In [203]:
np.dot(a,b)

26

In [204]:
a.shape = 2,1
b.shape = 1,2

In [205]:
a

array([[2],
       [3]])

In [206]:
b

array([[4, 6]])

In [207]:
a.shape

(2, 1)

In [208]:
b.shape

(1, 2)

In [209]:
np.dot(a,b)

array([[ 8, 12],
       [12, 18]])

In [210]:
np.dot(b,a)

array([[26]])

In [211]:
a = np.array([1,2,3])
b = np.array([1,2,4])
a == b

array([ True,  True, False])

In [212]:
np.logical_and(a,b)

array([ True,  True,  True])

In [213]:
np.logical_or(a,b)

array([ True,  True,  True])

In [215]:
np.logical_not(b)

array([False, False, False])

In [216]:
np.logical_xor(a,b)

array([False, False, False])

In [217]:
b

array([1, 2, 4])

随机模块

In [219]:
np.random.rand(10)

array([0.07101996, 0.67660151, 0.04319895, 0.61643311, 0.94689054,
       0.12332402, 0.43086093, 0.03796766, 0.65133342, 0.39103298])

In [220]:
np.random.randint(10,size=(5,4))

array([[4, 3, 2, 6],
       [5, 6, 6, 5],
       [6, 6, 8, 8],
       [8, 5, 3, 9],
       [6, 6, 0, 3]])

In [221]:
np.random.rand()

0.03499625075766766

In [223]:
np.random.random_sample()

0.8455538713501393

In [224]:
np.random.randint(0,10,3)

array([1, 9, 1])

In [226]:
a, sigma = 1,0.9  #高斯分布
np.random.normal(a,sigma,10)

array([ 0.32050054,  0.89803772,  0.48169405,  2.39536643,  0.56042431,
       -0.42167636,  2.29812259,  1.71068081,  2.33434017,  0.90812443])

In [228]:
np.set_printoptions(precision = 3)

In [229]:
a, sigma = 1,0.9  #高斯分布
np.random.normal(a,sigma,10)

array([-0.147, -0.041,  1.548, -0.432,  0.073,  1.048,  0.082,  1.3  ,
        1.82 ,  1.804])

#洗牌，打乱顺序

In [231]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [233]:
np.random.shuffle(a)
a

array([7, 8, 6, 1, 4, 2, 0, 9, 5, 3])

In [238]:
np.random.seed(0)  #随机种子
a, sigma = 1,0.9  #高斯分布
np.random.normal(a,sigma,10)

array([2.588, 1.36 , 1.881, 3.017, 2.681, 0.12 , 1.855, 0.864, 0.907,
       1.37 ])

In [239]:
%%writefile numpytest.txt
1 5 9 4 2 7
4 0 7 3 8 5

Writing numpytest.txt


In [245]:
data = []
with open("numpytest.txt") as f:
    for line in f.readlines():
        files = line.split()
        cur_data = [float(x) for x in files]
        data.append(cur_data)
data = np.array(data)
data

array([[1., 5., 9., 4., 2., 7.],
       [4., 0., 7., 3., 8., 5.]])

In [252]:
data = np.loadtxt("numpytest.txt",delimiter = ' ',skiprows =1 ) #usecols = (0,1,4) 指定使用哪几列
data

array([4., 0., 7., 3., 8., 5.])

In [254]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [256]:
np.savetxt("numpywrt.txt",a, fmt = '%.2f',delimiter = ',')

读写array结构

In [257]:
a = np.arange(10)
np.save('numpybin.npy',a)

In [273]:
b = np.load('numpybin.npy')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [274]:
np.savez('numpz.npz',x=a, y=b)

In [275]:
data = np.load("numpz.npz")

In [276]:
data.keys()

KeysView(<numpy.lib.npyio.NpzFile object at 0x00000239ADEAD940>)

In [278]:
z = np.zeros((5,5))
print('%d bytes' %(z.size * z.itemsize))

200 bytes


In [279]:
z.size

25

In [280]:
z.itemsize

8

In [284]:
print(help(np.info(np.add)))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [285]:
np.nonzero([1,4,0,2,3,0,9])

(array([0, 1, 3, 4, 6], dtype=int64),)

In [289]:
a = np.random.random((3,3))
a

array([[0.87 , 0.979, 0.799],
       [0.461, 0.781, 0.118],
       [0.64 , 0.143, 0.945]])

In [290]:
a.max()

0.978618342232764

In [292]:
a.min()

0.11827442586893322

In [293]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [296]:
b = np.pad(a, pad_width = 1,mode='constant', constant_values = 0)
b

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [297]:
print(help(np.pad))

Help on function pad in module numpy.lib.arraypad:

pad(array, pad_width, mode, **kwargs)
    Pads an array.
    
    Parameters
    ----------
    array : array_like of rank N
        Input array
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ((before_1, after_1), ... (before_N, after_N)) unique pad widths
        for each axis.
        ((before, after),) yields same before and after pad for each axis.
        (pad,) or int is a shortcut for before = after = pad width for all
        axes.
    mode : str or function
        One of the following string values or a user supplied function.
    
        'constant'
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum'
            Pads with the maximum value of all or part of the
            vector

In [298]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

矩阵归一化

In [299]:
a = np.random.random((5,5))
a_max = a.max()
a_min = a.min()
a = (a - a_min) / (a - a_max)
a

c:\program files\python37\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


array([[ -1.078,  -0.69 ,  -0.34 ,  -3.528,  -0.822],
       [ -1.309,  -0.   ,  -1.615,  -1.577,  -1.61 ],
       [-20.727,  -2.163,  -0.542,  -0.759,  -2.335],
       [ -0.045,  -2.015,  -2.052,  -0.246,  -0.128],
       [ -0.441,  -0.552,  -1.319,  -0.764,     inf]])

In [301]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)
print(np.intersect1d(a,b))

[2 4 2 0 3 2 0 7 5 9]
[0 2 7 2 9 2 3 3 2 3]
[0 2 3 7 9]


In [302]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorrow = np.datetime64('today', 'D') + np.timedelta64(1,'D')

In [303]:
yesterday

numpy.datetime64('2018-09-11')

In [304]:
today

numpy.datetime64('2018-09-12')

In [305]:
tommorrow

numpy.datetime64('2018-09-13')

In [306]:
np.arange('2017-10','2017-11',dtype='datetime64[D]')

array(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
       '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
       '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
       '2017-10-13', '2017-10-14', '2017-10-15', '2017-10-16',
       '2017-10-17', '2017-10-18', '2017-10-19', '2017-10-20',
       '2017-10-21', '2017-10-22', '2017-10-23', '2017-10-24',
       '2017-10-25', '2017-10-26', '2017-10-27', '2017-10-28',
       '2017-10-29', '2017-10-30', '2017-10-31'], dtype='datetime64[D]')

In [308]:
z = np.random.uniform(0,10,10)
z

array([2.647, 3.978, 5.528, 1.649, 3.698, 1.464, 5.696, 7.037, 2.885,
       4.333])

In [310]:
np.floor(z)

array([2., 3., 5., 1., 3., 1., 5., 7., 2., 4.])

In [311]:
z = np.zero(5)
z.flags.writeable = False
z[0] = 1

AttributeError: module 'numpy' has no attribute 'zero'

In [312]:
np.set_printoptions(threshold=5)  #np.nan
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [313]:
z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(z-v)).argmin()
print(z[index])

75.6106693865041
76


In [315]:
z = np.arange(10,dtype = np.int32)
print(z.dtype)
z = z.astype(np.float32)
print(z.dtype)

int32
float32


In [316]:
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [319]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[8 2 8]
 [4 3 0]
 [4 3 6]]
[[8 2 8]
 [4 3 0]
 [4 3 6]]


In [320]:
z = np.array([1,2,4,5,1,2,6,4])
np.bincount(z)

array([0, 2, 2, ..., 2, 1, 1], dtype=int64)

In [322]:
z = np.random.randint(0,10,(4,4,4,4))
print(z)
res = z.sum(axis = (-2, -1))
res

[[[[1 3 4 1]
   [1 0 7 8]
   [4 3 5 6]
   [3 2 9 8]]

  [[1 4 0 8]
   [3 9 5 5]
   [1 7 8 6]
   [4 7 3 5]]

  [[3 6 4 7]
   [3 0 5 9]
   [3 7 5 5]
   [8 0 8 3]]

  [[6 9 3 2]
   [7 0 3 0]
   [3 6 1 9]
   [2 9 4 9]]]


 [[[1 3 2 4]
   [9 7 4 9]
   [4 1 2 7]
   [2 3 9 7]]

  [[6 6 2 3]
   [6 0 8 0]
   [7 6 5 9]
   [6 5 2 7]]

  [[1 9 2 2]
   [5 6 4 2]
   [2 1 0 9]
   [0 2 8 3]]

  [[0 8 8 1]
   [0 5 8 2]
   [3 5 3 8]
   [6 4 6 3]]]


 [[[6 2 6 5]
   [5 9 4 6]
   [5 1 3 3]
   [8 9 5 5]]

  [[6 0 9 7]
   [5 1 5 6]
   [6 8 7 5]
   [3 2 9 9]]

  [[3 2 5 4]
   [1 5 8 3]
   [5 8 4 1]
   [7 8 1 2]]

  [[1 1 7 5]
   [0 4 1 1]
   [6 6 0 2]
   [3 7 9 2]]]


 [[[4 9 0 6]
   [9 2 4 7]
   [3 0 5 4]
   [0 2 3 1]]

  [[7 1 3 4]
   [1 7 4 0]
   [2 7 4 0]
   [2 6 9 2]]

  [[4 9 9 5]
   [4 4 9 8]
   [1 5 7 0]
   [1 3 9 2]]

  [[8 2 4 8]
   [2 9 8 7]
   [8 2 3 3]
   [6 0 3 6]]]]


array([[65, 76, 76, 73],
       [74, 78, 56, 70],
       [82, 88, 67, 55],
       [59, 59, 80, 79]])

In [323]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z [[1,0]]
z

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [324]:
z = np.random.randint(0,10,50)
print(z)
print(np.bincount(z).argmax())

[3 9 6 ... 8 5 5]
6


In [327]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5
print(z[np.argpartition(-z,n)[:n]])

[9999 9998 9996 9995 9997]


In [328]:
np.set_printoptions(threshold=np.nan)
z = np.random.randint(0,5,(10,3))
z

array([[4, 4, 4],
       [2, 0, 0],
       [0, 4, 4],
       [0, 3, 1],
       [2, 1, 1],
       [4, 0, 4],
       [4, 0, 4],
       [4, 4, 1],
       [0, 0, 2],
       [3, 1, 4]])

In [333]:
e = np.all(z[:,1:] == z[:,:-1],axis = 1)
print(e)

[ True False False False False False False False False False]


In [329]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,5])
np.all(a == b)

False

In [330]:
np.any(a == b)

True